### ISSUE TITLE
Round 2 ICO scam

### ISSUE THREAD

**Issue by Huub79** [neonexchange/ico-round2-lottery#1]
Hello..

Sorry for bothering you guys. Can imagine you are busy.

When trying to participate in second round NEX ico I followed a link from your twitter account.
Unfortunately this appeared to be a scam.,

All the GAS I saved for the NEX ICO (585) was now sent to the wrong address:

AdNXNexCTgRMeLEiWxqE2zPpfpmfWuyeWe

Any idea if this can still be fixed in some way??
Feel really hopeless right now…
Thanks.

![fake2](https://user-images.githubusercontent.com/5417835/45368226-9a393480-b5d2-11e8-87a2-0baf1318117c.png)
![ico-fake](https://user-images.githubusercontent.com/5417835/45368228-9ad1cb00-b5d2-11e8-9d1f-1182384f6040.png)

**Comment by Huub79** [comment]
Anyone?
My GAS is still on the scammer's account :(

**Comment by canesin** [comment]
This address is not associated with Nash, as you can check the URL and account. Unfortunately you have been a victim of a phishing scam and there is nothing our team can do. I am sorry for your loss.

If you used our extension it blocks several phishing websites (the extension was required for the sale) including the one above (so it would have blocked the attack).

Also, we repeated several times we will never ask anyone in any situation to send any value to any wallet address.

![image](https://user-images.githubusercontent.com/353648/56362625-a16c9480-61ea-11e9-9ccb-7777a177e066.png)
